In [1]:
import numpy as np
import time

In [2]:
#executoin performace

size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy array 
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")


python list time = 0.15605974197387695 seconds
numpy array time = 0.004770994186401367 seconds


In [3]:
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"python list size = {np_arr.nbytes} bytes")



python list size = 8000056000000 bytes
python list size = 8000000 bytes


In [4]:
#create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)


In [5]:
#2D array

arr2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2d,arr2d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [6]:
#create
arr1 = np.zeros((2, 3), dtype = "int64")
print(arr1, arr1.shape)


[[0 0 0]
 [0 0 0]] (2, 3)


In [7]:
arr2 = np.ones((2,4 ), dtype = "int64")
print(arr2, arr2.shape)

[[1 1 1 1]
 [1 1 1 1]] (2, 4)


In [8]:
arr3 = np.full((2,4 ), 56 ,dtype = "int64")
print(arr3, arr3.shape)

[[56 56 56 56]
 [56 56 56 56]] (2, 4)


In [9]:
arr4 = np.eye((4 ), dtype = "int64") #identity matrix 
print(arr4, arr4.shape)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] (4, 4)


In [10]:
arr5 = np.arange(0, 11, 2)
print(arr5, arr5.shape)

[ 0  2  4  6  8 10] (6,)


In [11]:
arr6 = np.linspace(1, 100, 4)
print(arr6, arr6.shape)

[  1.  34.  67. 100.] (4,)


In [12]:
#properties of array 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [13]:
#operation on array 
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [23]:
#indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])
print(arr2 [arr2 %2==0])

[1 2 4]
[2 4 6]


In [24]:
#2d indexing 
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[arr2> 2])
                

[3 4 5 6]


In [29]:
#slicing operation
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])
print(arr[1:])
print(arr[:])
print(arr[0:4+1])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]


In [36]:
#veiws vs copy
nums = [1, 2, 3, 4, 5]
sub_list= nums[0:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)

[1, 2, 3]
[200, 2, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[1 2 3 4 5]


In [46]:
#data type

#integer datatype
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype)
#float dtype
arr = np.array([1, 2, 3.1, 4, 5])
print(arr, arr.dtype)
#string datatype
arr = np.array([1, 2, 3, 4, 5, "moti"])
print(arr, arr.dtype)

#complex datatype
arr1 = np.array([3 + 4j])
arr2 = np.array([5 + 6j])
print(arr1 + arr2)
print(arr1 - arr2)

#object dtype

arr = np.array(["prime", {1, 2, 3}, 3.14])
print(arr, arr.dtype)


[1 2 3 4 5] int64
[1.  2.  3.1 4.  5. ] float64
['1' '2' '3' '4' '5' 'moti'] <U21
[8.+10.j]
[-2.-2.j]
['prime' {1, 2, 3} 3.14] object
